baseURL: https://uninotes.ryanbester.com/
languageCode: en-gb
title: University Notes
theme: hugo-book
copyright: 'Ryan Bester'

menu:
  after:
    - name: 🔒 Resources
      url: "https://github.com/ryanbester/uni-resources"

params:
  BookTheme: auto
  BookToC: true
  BookRepo: 'https://github.com/ryanbester/uni-notes'
  BookEditPath: 'edit/master'
  BookDateFormat: 'January 2, 2006'

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
